site_name: Systematically Improving RAG Applications
site_url: https://567-labs.github.io/systematically-improving-rag/
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: indigo
    accent: indigo
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - "Home": "index.md"
  - "Workshops":
      - "Overview": "workshops/index.md"
      - "Introduction": "workshops/chapter0.md"
      - "Chapter 1: Starting the Flywheel": "workshops/chapter1.md"
      - "Chapter 2: From Evaluation to Enhancement": "workshops/chapter2.md"
      - "Chapter 3: UX - Design Principles": "workshops/chapter3-1.md"
      - "Chapter 3: UX - Feedback Collection": "workshops/chapter3-2.md"
      - "Chapter 3: UX - Iterative Improvement": "workshops/chapter3-3.md"
      - "Chapter 4: Topic Modeling - Analysis": "workshops/chapter4-1.md"
      - "Chapter 4: Topic Modeling - Prioritization": "workshops/chapter4-2.md"
      - "Chapter 5: Multimodal - Understanding": "workshops/chapter5-1.md"
      - "Chapter 5: Multimodal - Implementation": "workshops/chapter5-2.md"
      - "Chapter 6: Architecture - Routing": "workshops/chapter6-1.md"
      - "Chapter 6: Architecture - Tools": "workshops/chapter6-2.md"
      - "Chapter 6: Architecture - Improvement": "workshops/chapter6-3.md"
  - "Office Hours":
      - "office-hours/index.md"
      - "FAQ": "office-hours/faq.md"
      - "Agents": "office-hours/AGENTS.md"
      - "Cohort 2":
        - "Week 1": "office-hours/cohort2/week1-summary.md"
        - "Week 2": "office-hours/cohort2/week2-summary.md"
        - "Week 3": "office-hours/cohort2/week3-summary.md"
        - "Week 4": "office-hours/cohort2/week4-summary.md"
        - "Week 5": "office-hours/cohort2/week5-summary.md"
        - "Week 6": "office-hours/cohort2/week6-summary.md"
      - "Cohort 3":
        - "Week 1":
          - "Session 1": "office-hours/cohort3/week-1-1.md"
          - "Session 2": "office-hours/cohort3/week-1-2.md"
        - "Week 2":
          - "Session 1": "office-hours/cohort3/week-2-1.md"
          - "Session 2": "office-hours/cohort3/week-2-2.md"
        - "Week 3":
          - "Session 1": "office-hours/cohort3/week-3-1.md"
        - "Week 4":
          - "Session 1": "office-hours/cohort3/week-4-1.md"
          - "Session 2": "office-hours/cohort3/week-4-2.md"
        - "Week 5":
          - "Session 1": "office-hours/cohort3/week-5-1.md"
          - "Session 2": "office-hours/cohort3/week-5-2.md"
  - "Talks":
      - "Overview": "talks/index.md"
      - "Autonomous Coding Agents w/ Nik Pash @ Cline": "talks/rag-is-dead-cline-nik.md"
      - "RAG Anti-patterns in the Wild": "talks/rag-antipatterns-skylar-payne.md"
      - "Semantic Search Over the Web with Exa": "talks/semantic-search-exa-will-bryk.md"
      - "Generative Evals": "talks/embedding-performance-generative-evals-kelly-hong.md"
      - "Online Evals and Production Monitoring": "talks/online-evals-production-monitoring-ben-sidhant.md"
      - "RAG Without APIs": "talks/rag-without-apis-browser-michael-struwig.md"
      - "Agentic RAG": "talks/colin-rag-agents.md"
      - "Document Ingestion and Parsing with Reducto": "talks/reducto-docs-adit.md"
      - "Enterprise Search and Fine-tuning Embedding Models": "talks/glean-manav.md"
      - "Lexical Search": "talks/john-lexical-search.md"
      - "Data Organization and Query Routing": "talks/query-routing-anton.md"
      - "Text Chunking Strategies": "talks/chromadb-anton-chunking.md"
      - "Encoder Stacking": "talks/superlinked-encoder-stacking.md"
      - "Fine-tuning Rerankers and Embeddings": "talks/fine-tuning-rerankers-embeddings-ayush-lancedb.md"
      - "Zapier's Evals with Vitor": "talks/zapier-vitor-evals.md"
  - "Resources":
      - "Learning Goals": "misc/learning-goals.md"
      - "Key Takeaways": "misc/what-i-want-you-to-takeaway.md"
      - "Introduction": "misc/introduction.md"
      - "Landing Page": "misc/landingpage.md"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jxnlco
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
