site_name: Systematically Improving RAG Applications
site_url: https://567-labs.github.io/systematically-improving-rag/
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - "Home": "index.md"
  - "Workshops":
      - "Overview": "workshops/index.md"
      - "Introduction": "workshops/chapter0.md"
      - "Chapter 1: Starting the Flywheel":
          - "Overview": "workshops/chapter1.md"
      - "Chapter 2: From Evaluation to Enhancement":
          - "Overview": "workshops/chapter2.md"
      - "Chapter 3: User Experience":
          - "Design Principles": "workshops/chapter3-1.md"
          - "Feedback Collection": "workshops/chapter3-2.md"
          - "Iterative Improvement": "workshops/chapter3-3.md"
      - "Chapter 4: Topic Modeling":
          - "Analysis": "workshops/chapter4-1.md"
          - "Prioritization": "workshops/chapter4-2.md"
      - "Chapter 5: Multimodal Capabilities":
          - "Understanding": "workshops/chapter5-1.md"
          - "Implementation": "workshops/chapter5-2.md"
      - "Chapter 6: Architecture":
          - "Routing": "workshops/chapter6-1.md"
          - "Tools": "workshops/chapter6-2.md"
          - "Improvement": "workshops/chapter6-3.md"
  - "Office Hours":
      - "office-hours/index.md"
      - "FAQ": "office-hours/faq.md"
      - "Agents": "office-hours/AGENTS.md"
      - "Chapter 1: Starting the Flywheel":
          - "Cohort 2 - Week 1": "office-hours/cohort2/week1-summary.md"
          - "Cohort 3 - Session 1": "office-hours/cohort3/week-1-1.md"
          - "Cohort 3 - Session 2": "office-hours/cohort3/week-1-2.md"
      - "Chapter 2: From Evaluation to Enhancement":
          - "Cohort 2 - Week 2": "office-hours/cohort2/week2-summary.md"
          - "Cohort 3 - Session 1": "office-hours/cohort3/week-2-1.md"
          - "Cohort 3 - Session 2": "office-hours/cohort3/week-2-2.md"
      - "Chapter 3: User Experience":
          - "Cohort 2 - Week 3": "office-hours/cohort2/week3-summary.md"
          - "Cohort 3 - Session 1": "office-hours/cohort3/week-3-1.md"
      - "Chapter 4: Topic Modeling":
          - "Cohort 2 - Week 4": "office-hours/cohort2/week4-summary.md"
          - "Cohort 3 - Session 1": "office-hours/cohort3/week-4-1.md"
          - "Cohort 3 - Session 2": "office-hours/cohort3/week-4-2.md"
      - "Chapter 5: Multimodal Capabilities":
          - "Cohort 2 - Week 5": "office-hours/cohort2/week5-summary.md"
          - "Cohort 3 - Session 1": "office-hours/cohort3/week-5-1.md"
          - "Cohort 3 - Session 2": "office-hours/cohort3/week-5-2.md"
      - "Chapter 6: Architecture":
          - "Cohort 2 - Week 6": "office-hours/cohort2/week6-summary.md"
  - "Talks":
      - "Overview": "talks/index.md"
      - "Search / Indexing / Chunking":
          - "Text Chunking Strategies (Anton, ChromaDB)": "talks/chromadb-anton-chunking.md"
          - "Lexical Search in RAG Applications (John Berryman)": "talks/john-lexical-search.md"
          - "Query Routing for RAG Systems (Anton, ChromaDB)": "talks/query-routing-anton.md"
          - "Semantic Search Over the Web with Exa (Will Bryk, Exa)": "talks/semantic-search-exa-will-bryk.md"
          - "RAG Without APIs: Browser-Based Retrieval (Michael, OpenBB)": "talks/rag-without-apis-browser-michael-struwig.md"
      - "Finetuning":
          - "Enterprise Search and Fine-tuning Embedding Models (Manav, Glean)": "talks/glean-manav.md"
          - "Fine-tuning Re-rankers and Embedding Models (Ayush, LanceDB)": "talks/fine-tuning-rerankers-embeddings-ayush-lancedb.md"
          - "Understanding Embedding Performance through Generative Evals (Kelly Hong)": "talks/embedding-performance-generative-evals-kelly-hong.md"
      - "Monitoring":
          - "Online Evals and Production Monitoring (Ben & Sidhant)": "talks/online-evals-production-monitoring-ben-sidhant.md"
          - "RAG Anti-patterns in the Wild (Skylar Payne)": "talks/rag-antipatterns-skylar-payne.md"
          - "Building Feedback Systems for AI Products (Vitor, Zapier)": "talks/zapier-vitor-evals.md"
      - "Coding Agents":
          - "Autonomous Coding Agents (Nik Pash, Cline)": "talks/rag-is-dead-cline-nik.md"
          - "Agentic RAG (Colin Flaherty)": "talks/colin-rag-agents.md"
      - "Document Processing":
          - "Better RAG Through Better Data (Adit, Reducto)": "talks/reducto-docs-adit.md"
          - "Encoder Stacking and Multi-Modal Retrieval (Daniel, Superlinked)": "talks/superlinked-encoder-stacking.md"
  - "Resources":
      - "Learning Goals": "misc/learning-goals.md"
      - "Key Takeaways": "misc/what-i-want-you-to-takeaway.md"
      - "Introduction": "misc/introduction.md"
      - "Landing Page": "misc/landingpage.md"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jxnlco
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
