site_name: The RAG Flywheel
site_url: https://567-labs.github.io/rag/
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - "Home": 
    - index.md
    - "Introduction": introduction.md
    - "Learning Goals": learning-goals.md
    - "What I want you to take away": what-i-want-you-to-takeaway.md
  - "Workshops":
    - "Overview": "workshops/index.md"
    - "Introduction": "workshops/chapter0.md"
    - "Chapter 1: Starting the Flywheel": "workshops/chapter1.md"
    - "Chapter 2: From Evaluation to Enhancement": "workshops/chapter2.md"
    - "Chapter 3 Part 1: Design Principles": "workshops/chapter3-1.md"
    - "Chapter 3 Part 2: Feedback Collection": "workshops/chapter3-2.md"
    - "Chapter 3 Part 3: Iterative Improvement": "workshops/chapter3-3.md"
    - "Chapter 4: Understanding Your Users": "workshops/chapter4.md"
    - "Chapter 5: Building Specialized Capabilities": "workshops/chapter5.md"
    - "Chapter 6: Unified Product Architecture": "workshops/chapter6.md"
  - "Office Hours":
    - "office-hours/index.md"
    - "Week 1": "office-hours/week1-summary.md"
    - "Week 2": "office-hours/week2-summary.md"
    - "Week 3": "office-hours/week3-summary.md"
    - "Week 4": "office-hours/week4-summary.md"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - social

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jxnlco
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
