site_name: The RAG Flywheel
site_url: https://567-labs.github.io/rag/
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - "Home": "index.md"
  - "Workshops":
      - "Overview": "workshops/index.md"
      - "Introduction": "workshops/chapter0.md"
      - "Chapter 1: Starting the Flywheel": "workshops/chapter1.md"
      - "Chapter 2: From Evaluation to Enhancement": "workshops/chapter2.md"
      - "Chapter 3: UX - Design Principles": "workshops/chapter3-1.md"
      - "Chapter 3: UX - Feedback Collection": "workshops/chapter3-2.md"
      - "Chapter 3: UX - Iterative Improvement": "workshops/chapter3-3.md"
      - "Chapter 4: Topic Modeling - Analysis": "workshops/chapter4-1.md"
      - "Chapter 4: Topic Modeling - Prioritization": "workshops/chapter4-2.md"
      - "Chapter 5: Multimodal - Understanding": "workshops/chapter5-1.md"
      - "Chapter 5: Multimodal - Implementation": "workshops/chapter5-2.md"
      - "Chapter 6: Architecture - Routing": "workshops/chapter6-1.md"
      - "Chapter 6: Architecture - Tools": "workshops/chapter6-2.md"
      - "Chapter 6: Architecture - Improvement": "workshops/chapter6-3.md"
  - "Office Hours":
      - "office-hours/index.md"
      - "Cohort 2":
        - "Week 1": "office-hours/cohort2/week1-summary.md"
        - "Week 2": "office-hours/cohort2/week2-summary.md"
        - "Week 3": "office-hours/cohort2/week3-summary.md"
        - "Week 4": "office-hours/cohort2/week4-summary.md"
        - "Week 5": "office-hours/cohort2/week5-summary.md"
      - "Cohort 3":
        - "Week 1":
          - "Session 1": "office-hours/cohort3/week-1-1.md"
        - "Week 2":
          - "Advanced RAG Strategies (C3W2S1)": "office-hours/cohort3/week-2-1.md"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - social

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jxnlco
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY